// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_kGAJKLzrWG5S6FgEnmPJdNPq3WVAigg',
    appId: '1:375817216927:web:377409f172af9c00b653aa',
    messagingSenderId: '375817216927',
    projectId: 'click-a839b',
    authDomain: 'click-a839b.firebaseapp.com',
    storageBucket: 'click-a839b.firebasestorage.app',
    measurementId: 'G-0KW9MJV636',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy53qzF1DZE2Z9fvhXw8J1dCiZEKz9lfE',
    appId: '1:375817216927:android:b7c5eeafa9d1f3e2b653aa',
    messagingSenderId: '375817216927',
    projectId: 'click-a839b',
    storageBucket: 'click-a839b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Mgh8nrNBApbuw7NaDHaaXxnqm-u8AtE',
    appId: '1:375817216927:ios:7ca271e122cea581b653aa',
    messagingSenderId: '375817216927',
    projectId: 'click-a839b',
    storageBucket: 'click-a839b.firebasestorage.app',
    iosBundleId: 'com.example.click',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-Mgh8nrNBApbuw7NaDHaaXxnqm-u8AtE',
    appId: '1:375817216927:ios:7ca271e122cea581b653aa',
    messagingSenderId: '375817216927',
    projectId: 'click-a839b',
    storageBucket: 'click-a839b.firebasestorage.app',
    iosBundleId: 'com.example.click',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_kGAJKLzrWG5S6FgEnmPJdNPq3WVAigg',
    appId: '1:375817216927:web:81cc40ae48c0e677b653aa',
    messagingSenderId: '375817216927',
    projectId: 'click-a839b',
    authDomain: 'click-a839b.firebaseapp.com',
    storageBucket: 'click-a839b.firebasestorage.app',
    measurementId: 'G-WRPXG3240M',
  );
}
